### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by trijobe** [AvailLang/Avail#133] opened 2019-10-23 03:04 UTC
```
[INTERNAL]: module "/alchemy/Test", line 74:
Internal error: class com.avail.descriptor.SendPhraseDescriptor.simpleName does not meaningfully implement o_MacroOriginalSendNode
com.avail.exceptions.AvailUnsupportedOperationException: class com.avail.descriptor.SendPhraseDescriptor.simpleName does not meaningfully implement o_MacroOriginalSendNode
	at com.avail.descriptor.AbstractDescriptor.unsupportedOperationException(AbstractDescriptor.java:1206)
	at com.avail.descriptor.Descriptor.o_MacroOriginalSendNode(Descriptor.java:4608)
	at com.avail.descriptor.AvailObject.macroOriginalSendNode(AvailObject.java:5721)
	at com.avail.compiler.AvailCompiler.reportAmbiguousInterpretations(AvailCompiler.java:933)
	at com.avail.compiler.AvailCompiler.lambda$tryIfUnambiguousThen$2(AvailCompiler.java:640)
	at com.avail.compiler.CompilationContext.lambda$setNoMoreWorkUnits$0(CompilationContext.java:259)
	at com.avail.compiler.CompilationContext.lambda$workUnitCompletion$2(CompilationContext.java:540)
	at com.avail.compiler.CompilationContext.lambda$workUnitsDo$3(CompilationContext.java:590)
	at com.avail.AvailTask.run(AvailTask.java:258)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Error (above) wasn't handled gracefully. Here's the code:

```
Module
	"Test"
Uses
	"Avail" = (
		-"_`!",
		…
	)


Extends
	"Avail" = (
		"keyword lexer",
        "whitespace lexer",
        "whole number lexer",
        "operator lexer",
        "…#"
	)

Entries
	"Hello World",
	"_`!"
Body

Print: "Building\n";

/**
 *Print a traditional greeting to standard output.
 *
 *@entry
 *@method "Hello World"
 *@returns "⊤"
 */
Private method "Hello World" is
[
	Print: "Hello world!\n";
];

/**
 *Compute the factorial of {@param "n"}.
 *
 *@entry
 *@method "_`!"
 *@param "n" "whole number"
 *@returns "whole number"
 */

Abstract method "_`!" is [whole number]→whole number;

Private method "_`!" is
[
	n : {0, 1}ᵀ
|
	1
];

Private method "_`!" is
[
	n : [2..∞)
|
	n × (n-1)!
] : whole number;
```

**Comment by toddATavail** [comment] 2019-10-23 03:05
Tristan and I ran into this during a teaching lesson.

**Comment by toddATavail** [comment] 2019-10-23 03:13
It looks like this bug only exists in master, not development. It seems to be fixed there. So you can close this issue.

**Comment by markATavail** [comment] 2019-10-23 03:14
I'll still explore it, then shut it down if I can't reproduce it.

**Comment by markATavail** [comment] 2019-10-23 03:53
Ah, yes.  I remember creating a very detailed, expressive patch for this exact problem a couple of months ago.  I guess the patch isn't in master yet.

**Closed** 2019-10-23 03:54 UTC
Labels: bug
