### ISSUE TITLE
Anvil runs out of file handles

### ISSUE THREAD

**Issue by markATavail** [AvailLang/Avail#282] opened 2023-08-25 17:22 UTC
Running Anvil for several days led to exhaustion of file handles.  This cascaded into a problem reading source when refreshing open editors, which led to an error message being written into the editor instead.  That error message was then autosaved, destroying the files.

The file-destroying behavior has been emergency-fixed directly on development, but the underlying cause of file handle exhaustion still needs to be addressed.

**Comment by richATavail** [comment] 2023-08-26 14:22
I have confirmed that a new file handle is opened with each save/autosave, however the file is not closed causing growth. This is tested using a single file, `Avail Tests.avail`. With each change a new file handle is created, but never cleaned up. The following image shows the open files for `Avail Tests.avail` by running `lsof -p<PID> | grep "Avail Tests.avail"` after each singular edit. Notice how the number of occurrences of that file handle increases by one each time.

<img width="1328" alt="image" src="https://github.com/AvailLang/Avail/assets/13374407/781fdc00-4da6-48d9-aa63-41070e267b8e">

This is caused by a bug in `FileSystemModuleRootResolver.saveFile` where the file is not closed after write.

**Comment by richATavail** [comment] 2023-08-26 14:30
Causing the save to close the file upon completion solves the issue as demonstrated here. The following image was taken by using the IntelliJ debugger in combination with the test performed in the previous comment.  A break point was placed at the location right before the file is to be closed in `saveFile` to demonstrate the file being open. The `lsof` command is then run to see the file open. The debugger is then played through and the `lsof` file is run again to show the file is closed.
<img width="1331" alt="image" src="https://github.com/AvailLang/Avail/assets/13374407/eb3b887a-28d4-4f91-bb9d-fac62490e3b1">

**Closed** 2023-09-08 04:37 UTC
